apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-pv-volume
  labels:
    type: local
spec:
  storageClassName: mailu-pv
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/stoapp/conf/mail/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-hdd
  namespace: mailu-mailserver
spec:
  storageClassName: mailu-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage
  namespace: mailu-mailserver
spec:
  storageClassName: mailu-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
